name: Hello World
on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        # ref: main -> clone branch main on the server
        # fetch-depth: 1 -> clone only latest commit
        with:
          ref: main
          fetch-depth: 1
